Repository carson-katri/dream-textures, pull requests merged in 2022-10, with the labels that each got.

#160 Fixed context bug "AttributeError: 'SpaceDopeSheetEditor' object has …
  ui/panel.py
Labels: bug

#186 Fix some install issues
  __init__.py
  preferences.py
Labels: bug

#204 Subprocess IPC improvements
  generator_process.py
  operators/dream_texture.py
Labels: refactor

#274 More Subprocess Refactoring and Cancel Generate Operator
  classes.py
  generator_process.py
  operators/dream_texture.py
  operators/upscale.py
  ui/panels/dream_texture.py
Labels: refactor

#299 delete pointers before closing shared memory
  render_pass.py
Labels: bug

#317 Import Fixes
  generator_process.py
Labels: bug

#318 Upscale Seamless Fix
  __init__.py
  generator_process.py
  operators/upscale.py
  ui/panels/upscaling.py
Labels: enhancement, upscaling

#332 Add File Batch and Re-Enable Iterations
  __init__.py
  generator_process/intents/prompt_to_image.py
  operators/dream_texture.py
  prompt_engineering.py
  property_groups/dream_prompt.py
  ui/panels/dream_texture.py
Labels: enhancement

#333 Fix InpaintAreaBrush behavior
  classes.py
  operators/inpaint_area_brush.py
Labels: bug

#335 Add Asymmetric Tiling
  generator_process/intents/prompt_to_image.py
  property_groups/dream_prompt.py
  ui/panels/dream_texture.py
Labels: enhancement

#336 Add section linking to GH contributors
  __init__.py
  classes.py
  preferences.py
Labels: documentation
